debug: false
logging:
  pattern:
    console:

spring:
  application:
    name: MindMcpServer
  ai:
    mcp:
      server:
        name: MindMcpServer
        version: 0.0.1
        protocol: STREAMABLE
        streamable-http:
          mcp-endpoint: /mcp
  main:
    banner-mode: off
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerAutoConfiguration
      - org.springframework.boot.autoconfigure.security.oauth2.client.servlet.OAuth2ClientAutoConfiguration

server:
  port: 8080

mind:
  username: ${MIND_USERNAME}
  password: ${MIND_PASSWORD}
  base_url: ${MIND_BASE_URL}
  timezone: ${MIND_TIMEZONE}
  notification_service_id: ${NOTIFICATION_SERVICE_ID}

---
spring:
  config:
    activate:
      on-profile: stdio
  ai:
    mcp:
      server:
        stdio: true
  main:
    web-application-type: none
