version: "3.9"

services:
  mind-mcp:
    image: flyingtoaster0/mind-mcp:latest
    environment:
      - REDIS_HOST=redis
      - MIND_USERNAME=${MIND_USERNAME}
      - MIND_PASSWORD=${MIND_PASSWORD}
      - MIND_BASE_URL=${MIND_BASE_URL}
      - MIND_TIMEZONE=${MIND_TIMEZONE}
      - NOTIFICATION_SERVICE_ID=${NOTIFICATION_SERVICE_ID}
    ports:
      - "8080:8080"
    restart: "no"
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: mind-mcp-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  redis_data:
