version: "3.9"

services:
  supergateway:
    build: .
    #image: supercorp/supergateway
    command: >
      --stdio "REDIS_HOST=redis MIND_USERNAME=${MIND_USERNAME} MIND_PASSWORD=${MIND_PASSWORD} MIND_BASE_URL=${MIND_BASE_URL} MIND_TIMEZONE=${MIND_TIMEZONE} java -jar /mind-mcp.jar"
      --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./mind-mcp.jar:/mind-mcp.jar
    environment:
      - MIND_USERNAME=flyingtoaster0
      - MIND_PASSWORD=wtO6qTRTeugPBV7PV8vEiAhgrR7f2IHA
      - MIND_BASE_URL=http://10.88.111.213:8086/api
      - MIND_TIMEZONE=America/Toronto
      - REDIS_HOST=redis
    stdin_open: true   # same as -it
    tty: true          # same as -it
    restart: "no"      # same as --rm (container won't restart)

  redis:
    image: redis:7
    container_name: mind-mcp-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

  mind:
    container_name: mind
    image: mrcas/mind:latest
    volumes:
      - "mind-db:/app/db"
    environment:
      - TZ=America/Toronto
    ports:
      - 8086:8080
    restart: always

volumes:
  redis_data:
  mind-db:
